// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrhmxgfcobcpsnrxguli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yaG14Z2Zjb2JjcHNucnhndWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDg3MTgsImV4cCI6MjA3NDQ4NDcxOH0.yAXuU7Uj7vqX-rGjqSw4AX76IQnp5ucIlqSQ1Muo8Cg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});